In [ ]:
#loading data into dataframes
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
path="/content/drive/MyDrive/Colab Notebooks/data/SCADA.csv"
df1 = pd.read_csv(path)
path1="/content/drive/MyDrive/Colab Notebooks/data/PSCADA.csv"
df=pd.read_csv(path1)

Mounted at /content/drive


In [ ]:
#adding the is_Attack,is_user_operating columns to dataframe
df1['is_user_operating']=df['is_user_operating']
df1['is_attack'] = df['is_attack']

In [ ]:
#removing unnecessary columns
df1 = df1.drop(columns=['src','timestamp'])

In [ ]:
#train and test split
from sklearn.model_selection import train_test_split
train, test = train_test_split(df1, test_size=0.2, random_state=42)

In [ ]:
#splitting of training data
local_train,local_test = train_test_split(train,test_size=0.2,random_state=75)

In [ ]:
d1_train=local_train
d2_train=local_train
d3_train=local_train
d1_test=local_test
d2_test=local_test
d3_test=local_test

In [ ]:
#dropping columns from the dataframes based on the models
d1_train=d1_train.drop(columns=['cpu_time.iowait','cpu_time.irq','memory_percent','conn_count.udp','tcp_state.listen'])
d2_train=d2_train.drop(columns=['net_byte.tx','net_byte.rx','net_pkt.tx','net_pkt.rx','conn_count.tcp','conn_count.udp','tcp_state.listen','tcp_state.established','is_user_operating'])
d3_train=d3_train.drop(columns=['cpu_percent','cpu_time.user','cpu_time.sys','cpu_time.idle','cpu_time.nice','cpu_time.iowait','cpu_time.irq','cpu_time.softirq','memory_percent','is_user_operating'])
d1_test=d1_test.drop(columns=['cpu_time.iowait','cpu_time.irq','memory_percent','conn_count.udp','tcp_state.listen'])
d2_test=d2_test.drop(columns=['net_byte.tx','net_byte.rx','net_pkt.tx','net_pkt.rx','conn_count.tcp','conn_count.udp','tcp_state.listen','tcp_state.established','is_user_operating'])
d3_test=d3_test.drop(columns=['cpu_percent','cpu_time.user','cpu_time.sys','cpu_time.idle','cpu_time.nice','cpu_time.iowait','cpu_time.irq','cpu_time.softirq','memory_percent','is_user_operating'])

In [ ]:
final_y = test['is_attack']
final_d1=test.drop(columns=['cpu_time.iowait','cpu_time.irq','memory_percent','conn_count.udp','tcp_state.listen','is_attack'])
final_d2=test.drop(columns=['net_byte.tx','net_byte.rx','net_pkt.tx','net_pkt.rx','conn_count.tcp','conn_count.udp','tcp_state.listen','tcp_state.established','is_user_operating','is_attack'])
final_d3=test.drop(columns=['cpu_percent','cpu_time.user','cpu_time.sys','cpu_time.idle','cpu_time.nice','cpu_time.iowait','cpu_time.irq','cpu_time.softirq','memory_percent','is_user_operating','is_attack'])


In [ ]:
d1_test_y=d1_test['is_attack']
d1_test_x=d1_test.drop(columns=['is_attack'])

d1_train_y=d1_train['is_attack']
d1_train_x=d1_train.drop(columns=['is_attack'])

d2_test_y=d2_test['is_attack']
d2_test_x=d2_test.drop(columns=['is_attack'])

d2_train_y=d2_train['is_attack']
d2_train_x=d2_train.drop(columns=['is_attack'])

d3_test_y=d3_test['is_attack']
d3_test_x=d3_test.drop(columns=['is_attack'])

d3_train_y=d3_train['is_attack']
d3_train_x=d3_train.drop(columns=['is_attack'])

In [ ]:
#Decisiontree classifier - 95.367%
from sklearn import tree
 
#choose from different tunable hyper parameters
clf1 = tree.DecisionTreeClassifier(criterion='entropy')
clf2 = tree.DecisionTreeClassifier(criterion='entropy')
clf3 = tree.DecisionTreeClassifier(criterion='entropy')
 
#Printing all the parameters of Decision Trees
print(clf1,clf2,clf3)
 
#Creating the model on Training Data
DTree1=clf1.fit(d1_train_x,d1_train_y)
pred1=DTree1.predict(d1_test_x)

print(pred1)

DTree2=clf2.fit(d2_train_x,d2_train_y)
pred2=DTree2.predict(d2_test_x)

print(pred2)

DTree3=clf3.fit(d3_train_x,d3_train_y)
pred3=DTree3.predict(d3_test_x)

print(pred3)

DecisionTreeClassifier(criterion='entropy') DecisionTreeClassifier(criterion='entropy') DecisionTreeClassifier(criterion='entropy')
[1 0 0 ... 0 0 0]
[1 0 1 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [ ]:
#Random forest - 95.31%
from sklearn.ensemble import RandomForestClassifier
# Instantiate model with 10000 decision trees
rf1 = RandomForestClassifier(n_estimators = 2000, random_state = 42)
rf2 = RandomForestClassifier(n_estimators = 2000, random_state = 42)
rf3 = RandomForestClassifier(n_estimators = 2000, random_state = 42)
# Train the model on training data
rf1.fit(d1_train_x, d1_train_y);
pred1 = rf1.predict(d1_test_x)

rf2.fit(d2_train_x, d2_train_y);
pred2 = rf2.predict(d2_test_x)

rf3.fit(d3_train_x, d3_train_y);
pred3 = rf3.predict(d3_test_x)

In [ ]:
#Gaussian NB - 64.6%
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
gnb1 = GaussianNB()
gnb2 = GaussianNB()
gnb3 = GaussianNB()

gnb1.fit(d1_train_x, d1_train_y)
pred1 = gnb1.predict(d1_test_x)

gnb2.fit(d2_train_x, d2_train_y)
pred2=gnb2.predict(d2_test_x)

gnb3.fit(d3_train_x, d3_train_y)
pred3=gnb3.predict(d3_test_x)


In [ ]:
#SVC - 64.69%
from sklearn.svm import SVC
svc1 = SVC()
svc2 = SVC()
svc3 = SVC()

svc1.fit(d1_train_x, d1_train_y)
pred1 = svc1.predict(d1_test_x)

svc2.fit(d2_train_x,d2_train_y)
pred2 = svc2.predict(d2_test_x)

svc3.fit(d3_train_x,d3_train_y)
pred3 = svc3.predict(d3_test_x)

In [ ]:
#KNN - 95.06%
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors=2)
knn2 = KNeighborsClassifier(n_neighbors=2)
knn3 = KNeighborsClassifier(n_neighbors=2)

knn1.fit(d1_train_x, d1_train_y)
pred1 = knn1.predict(d1_test_x)

knn2.fit(d2_train_x, d2_train_y)
pred2 = knn2.predict(d2_test_x)

knn3.fit(d3_train_x, d3_train_y)
pred3 = knn3.predict(d3_test_x)

In [ ]:
from sklearn import metrics

print(pred1)
print(metrics.classification_report(d1_test_y, pred1))
cm1 = metrics.confusion_matrix(d1_test_y, pred1)
print("confusion_matrix: ",cm1)
print("accuracy ",(cm1[0][0]+cm1[1][1])/(cm1[0][0]+cm1[0][1]+cm1[1][1]+cm1[1][0]))


print(metrics.classification_report(d2_test_y, pred2))
cm2 = metrics.confusion_matrix(d2_test_y, pred2)
print("confusion_matrix: ",cm2)
print("accuracy ",(cm2[0][0]+cm2[1][1])/(cm2[0][0]+cm2[0][1]+cm2[1][1]+cm2[1][0]))


print(metrics.classification_report(d3_test_y, pred3))
cm3 = metrics.confusion_matrix(d3_test_y, pred3)
print("confusion_matrix: ",cm3)
print("accuracy ",(cm3[0][0]+cm3[1][1])/(cm3[0][0]+cm3[0][1]+cm3[1][1]+cm3[1][0]))

[1 0 0 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.91      0.99      0.95      9332
           1       0.99      0.89      0.94      7904

    accuracy                           0.94     17236
   macro avg       0.95      0.94      0.94     17236
weighted avg       0.95      0.94      0.94     17236

confusion_matrix:  [[9252   80]
 [ 879 7025]]
accuracy  0.9443606405198421
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9332
           1       1.00      1.00      1.00      7904

    accuracy                           1.00     17236
   macro avg       1.00      1.00      1.00     17236
weighted avg       1.00      1.00      1.00     17236

confusion_matrix:  [[9324    8]
 [   9 7895]]
accuracy  0.9990136922719889
              precision    recall  f1-score   support

           0       0.91      1.00      0.95      9332
           1       1.00      0.89      0.94      7904

    accuracy  

In [ ]:
#DecisionTree
R1=DTree1.predict(final_d1)
R2=DTree2.predict(final_d2)
R3=DTree3.predict(final_d3)
print(len(R1),len(R2),len(R3))

21545 21545 21545


In [ ]:
#Randomforest
R1= rf1.predict(final_d1)
R2= rf2.predict(final_d2)
R3= rf3.predict(final_d3)


In [ ]:
#GNB
R1 = gnb1.predict(final_d1)
R2=gnb2.predict(final_d2)
R3 = gnb3.predict(final_d3)

In [ ]:
#SVC
R1 = svc1.predict(final_d1)
R2=svc2.predict(final_d2)
R3 = svc3.predict(final_d3)

In [ ]:
#KNN
R1 = knn1.predict(final_d1)
R2=knn2.predict(final_d2)
R3 = knn3.predict(final_d3)

In [ ]:
#KNN,RFT,DT
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

for i in range(10):
  knn = KNeighborsClassifier(n_neighbors=2)
  knn.fit(d1_train_x, d1_train_y)
  rf = RandomForestClassifier(n_estimators = 2000, random_state = 42+i)
  rf.fit(d2_train_x, d2_train_y);
  clf = tree.DecisionTreeClassifier(criterion='entropy')
  clf1=clf.fit(d3_train_x,d3_train_y)
R1 = knn.predict(final_d1)
R2=rf.predict(final_d2)
R3 = clf1.predict(final_d3)  

In [ ]:
#Final
from sklearn import metrics
print(metrics.classification_report(l, final_y))
cm4 = metrics.confusion_matrix(l, final_y)
print("confusion_matrix: ",cm4)
print("accuracy ",(cm4[0][0]+cm4[1][1])/(cm4[0][0]+cm4[0][1]+cm4[1][1]+cm4[1][0]))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96     12820
           1       0.90      1.00      0.94      8725

    accuracy                           0.95     21545
   macro avg       0.95      0.96      0.95     21545
weighted avg       0.96      0.95      0.95     21545

confusion_matrix:  [[11799  1021]
 [   10  8715]]
accuracy  0.9521466697609654


Code to train with different models


In [ ]:
import numpy

#KNN,DT,RF

for i in range(10):
  knn = KNeighborsClassifier(n_neighbors=2)
  knn.fit(d1_train_x, d1_train_y)

  clf = tree.DecisionTreeClassifier(criterion='entropy')
  clf1=clf.fit(d2_train_x,d2_train_y)

  rf = RandomForestClassifier(n_estimators = 2000, random_state = 42+i)
  rf.fit(d3_train_x, d3_train_y);
  
R1 = knn.predict(final_d1)
R2=rf.predict(final_d3)
R3 = clf1.predict(final_d2)
#Voter

count1,count0=0,0
l=[]
for i in range(len(R1)):
  if(R1[i]==0):
    count0+=1
  if(R2[i]==0):
    count0+=1
  if(R3[i]==0):
    count0+=1
  if(R1[i]==1):
    count1+=1
  if(R2[i]==1):
    count1+=1
  if(R3[i]==1):
    count1+=1
  if(count0>count1):
    l.append(0)
  if(count0<count1):
    l.append(1)
  count0,count1=0,0
l=numpy.array(l)
print(l)                
#Final
from sklearn import metrics
print(metrics.classification_report(l, final_y))
cm4 = metrics.confusion_matrix(l, final_y)
print("confusion_matrix: ",cm4)
print("accuracy ",(cm4[0][0]+cm4[1][1])/(cm4[0][0]+cm4[0][1]+cm4[1][1]+cm4[1][0]))

[1 0 1 ... 0 0 0]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96     12818
           1       0.90      1.00      0.94      8727

    accuracy                           0.95     21545
   macro avg       0.95      0.96      0.95     21545
weighted avg       0.96      0.95      0.95     21545

confusion_matrix:  [[11797  1021]
 [   12  8715]]
accuracy  0.9520538407983291


In [ ]:
#RF,KNN,DT
for i in range(10):
  knn = KNeighborsClassifier(n_neighbors=2)
  knn.fit(d2_train_x, d2_train_y)
  rf = RandomForestClassifier(n_estimators = 2000, random_state = 42+i)
  rf.fit(d1_train_x, d1_train_y);
  clf = tree.DecisionTreeClassifier(criterion='entropy')
  clf1=clf.fit(d3_train_x,d3_train_y)
R1 = knn.predict(final_d2)
R2=rf.predict(final_d1)
R3 = clf1.predict(final_d3) 
#Voter
import numpy
count1,count0=0,0
l=[]
for i in range(len(R1)):
  if(R1[i]==0):
    count0+=1
  if(R2[i]==0):
    count0+=1
  if(R3[i]==0):
    count0+=1
  if(R1[i]==1):
    count1+=1
  if(R2[i]==1):
    count1+=1
  if(R3[i]==1):
    count1+=1
  if(count0>count1):
    l.append(0)
  if(count0<count1):
    l.append(1)
  count0,count1=0,0
l=numpy.array(l)
print(l)                
#Final
from sklearn import metrics
print(metrics.classification_report(l, final_y))
cm4 = metrics.confusion_matrix(l, final_y)
print("confusion_matrix: ",cm4)
print("accuracy ",(cm4[0][0]+cm4[1][1])/(cm4[0][0]+cm4[0][1]+cm4[1][1]+cm4[1][0]))

[1 0 1 ... 0 0 0]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96     12814
           1       0.90      1.00      0.95      8731

    accuracy                           0.95     21545
   macro avg       0.95      0.96      0.95     21545
weighted avg       0.96      0.95      0.95     21545

confusion_matrix:  [[11806  1008]
 [    3  8728]]
accuracy  0.9530749593873289


In [ ]:
#RF,DT,KNN
for i in range(10):
  knn = KNeighborsClassifier(n_neighbors=2)
  knn.fit(d3_train_x, d3_train_y)
  rf = RandomForestClassifier(n_estimators = 2000, random_state = 42+i)
  rf.fit(d1_train_x, d1_train_y);
  clf = tree.DecisionTreeClassifier(criterion='entropy')
  clf1=clf.fit(d2_train_x,d2_train_y)
R1 = knn.predict(final_d3)
R2=rf.predict(final_d1)
R3 = clf1.predict(final_d2)
#Voter
import numpy
count1,count0=0,0
l=[]
for i in range(len(R1)):
  if(R1[i]==0):
    count0+=1
  if(R2[i]==0):
    count0+=1
  if(R3[i]==0):
    count0+=1
  if(R1[i]==1):
    count1+=1
  if(R2[i]==1):
    count1+=1
  if(R3[i]==1):
    count1+=1
  if(count0>count1):
    l.append(0)
  if(count0<count1):
    l.append(1)
  count0,count1=0,0
l=numpy.array(l)
print(l)                
#Final
from sklearn import metrics
print(metrics.classification_report(l, final_y))
cm4 = metrics.confusion_matrix(l, final_y)
print("confusion_matrix: ",cm4)
print("accuracy ",(cm4[0][0]+cm4[1][1])/(cm4[0][0]+cm4[0][1]+cm4[1][1]+cm4[1][0]))


[1 0 1 ... 0 0 0]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96     12818
           1       0.90      1.00      0.95      8727

    accuracy                           0.95     21545
   macro avg       0.95      0.96      0.95     21545
weighted avg       0.96      0.95      0.95     21545

confusion_matrix:  [[11809  1009]
 [    0  8727]]
accuracy  0.9531677883499652


In [ ]:
#DT,KNN,RF
for i in range(10):
  knn = KNeighborsClassifier(n_neighbors=2)
  knn.fit(d2_train_x, d2_train_y)
  rf = RandomForestClassifier(n_estimators = 2000, random_state = 42+i)
  rf.fit(d3_train_x, d3_train_y);
  clf = tree.DecisionTreeClassifier(criterion='entropy')
  clf1=clf.fit(d1_train_x,d1_train_y)
R1 = knn.predict(final_d2)
R2=rf.predict(final_d3)
R3 = clf1.predict(final_d1)
#Voter
import numpy
count1,count0=0,0
l=[]
for i in range(len(R1)):
  if(R1[i]==0):
    count0+=1
  if(R2[i]==0):
    count0+=1
  if(R3[i]==0):
    count0+=1
  if(R1[i]==1):
    count1+=1
  if(R2[i]==1):
    count1+=1
  if(R3[i]==1):
    count1+=1
  if(count0>count1):
    l.append(0)
  if(count0<count1):
    l.append(1)
  count0,count1=0,0
l=numpy.array(l)
print(l)                
#Final
from sklearn import metrics
print(metrics.classification_report(l, final_y))
cm4 = metrics.confusion_matrix(l, final_y)
print("confusion_matrix: ",cm4)
print("accuracy ",(cm4[0][0]+cm4[1][1])/(cm4[0][0]+cm4[0][1]+cm4[1][1]+cm4[1][0]))

[1 0 1 ... 0 0 0]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96     12801
           1       0.90      1.00      0.95      8744

    accuracy                           0.95     21545
   macro avg       0.95      0.96      0.95     21545
weighted avg       0.96      0.95      0.95     21545

confusion_matrix:  [[11805   996]
 [    4  8740]]
accuracy  0.9535855186818287


In [ ]:
#DT,RF,KNN
for i in range(10):
  knn = KNeighborsClassifier(n_neighbors=2)
  knn.fit(d3_train_x, d3_train_y)
  rf = RandomForestClassifier(n_estimators = 2000, random_state = 42+i)
  rf.fit(d2_train_x, d2_train_y);
  clf = tree.DecisionTreeClassifier(criterion='entropy')
  clf1=clf.fit(d1_train_x,d1_train_y)
R1 = knn.predict(final_d3)
R2=rf.predict(final_d2)
R3 = clf1.predict(final_d1)
#Voter
import numpy
count1,count0=0,0
l=[]
for i in range(len(R1)):
  if(R1[i]==0):
    count0+=1
  if(R2[i]==0):
    count0+=1
  if(R3[i]==0):
    count0+=1
  if(R1[i]==1):
    count1+=1
  if(R2[i]==1):
    count1+=1
  if(R3[i]==1):
    count1+=1
  if(count0>count1):
    l.append(0)
  if(count0<count1):
    l.append(1)
  count0,count1=0,0
l=numpy.array(l)
print(l)                
#Final
from sklearn import metrics
print(metrics.classification_report(l, final_y))
cm4 = metrics.confusion_matrix(l, final_y)
print("confusion_matrix: ",cm4)
print("accuracy ",(cm4[0][0]+cm4[1][1])/(cm4[0][0]+cm4[0][1]+cm4[1][1]+cm4[1][0]))

[1 0 1 ... 0 0 0]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96     12800
           1       0.90      1.00      0.95      8745

    accuracy                           0.95     21545
   macro avg       0.95      0.96      0.95     21545
weighted avg       0.96      0.95      0.95     21545

confusion_matrix:  [[11807   993]
 [    2  8743]]
accuracy  0.9538175910884196


In [ ]:
#Voter
import numpy
count1,count0=0,0
l=[]
for i in range(len(R1)):
  if(R1[i]==0):
    count0+=1
  if(R2[i]==0):
    count0+=1
  if(R3[i]==0):
    count0+=1
  if(R1[i]==1):
    count1+=1
  if(R2[i]==1):
    count1+=1
  if(R3[i]==1):
    count1+=1
  if(count0>count1):
    l.append(0)
  if(count0<count1):
    l.append(1)
  count0,count1=0,0
l=numpy.array(l)
print(l)                


[1 0 1 ... 0 0 0]


In [ ]:
from matplotlib import pyplot as plt
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier 
from sklearn import tree
from IPython.display import Image
import pydotplus 

#Decisiontree classifier - 95.367%
from sklearn import tree
 
#choose from different tunable hyper parameters
clf1 = tree.DecisionTreeClassifier(criterion='entropy',max_depth=5)
clf2 = tree.DecisionTreeClassifier(criterion='entropy',max_depth=5)
clf3 = tree.DecisionTreeClassifier(criterion='entropy',max_depth=5)
 
#Printing all the parameters of Decision Trees
print(clf1,clf2,clf3)
 
#Creating the model on Training Data
DTree1=clf1.fit(d1_train_x,d1_train_y)
pred1=DTree1.predict(d1_test_x)

print(pred1)

DTree2=clf2.fit(d2_train_x,d2_train_y)
pred2=DTree2.predict(d2_test_x)

print(pred2)

DTree3=clf3.fit(d3_train_x,d3_train_y)
pred3=DTree3.predict(d3_test_x)

print(pred3)


#DecisionTree
R1=DTree1.predict(final_d1)
R2=DTree2.predict(final_d2)
R3=DTree3.predict(final_d3)
print(len(R1),len(R2),len(R3))

#Voter
import numpy
count1,count0=0,0
l=[]
for i in range(len(R1)):
  if(R1[i]==0):
    count0+=1
  if(R2[i]==0):
    count0+=1
  if(R3[i]==0):
    count0+=1
  if(R1[i]==1):
    count1+=1
  if(R2[i]==1):
    count1+=1
  if(R3[i]==1):
    count1+=1
  if(count0>count1):
    l.append(0)
  if(count0<count1):
    l.append(1)
  count0,count1=0,0
l=numpy.array(l)
print(l)                

from sklearn import metrics
print(metrics.classification_report(l, final_y))
cm4 = metrics.confusion_matrix(l, final_y)
print("confusion_matrix: ",cm4)
print("accuracy ",(cm4[0][0]+cm4[1][1])/(cm4[0][0]+cm4[0][1]+cm4[1][1]+cm4[1][0]))

FNames1 = d1_train_x.columns.values
FNames2 = d2_train_x.columns.values
FNames3 = d3_train_x.columns.values

CNames= ['0','1']

dot_data1 = tree.export_graphviz(DTree1,out_file=None,feature_names=FNames1,class_names=CNames)

graph1 = pydotplus.graph_from_dot_data(dot_data1)

Image(graph1.create_png())
graph1.write_png("UserBehaviourDT.png")

dot_data2 = tree.export_graphviz(DTree2,out_file=None,feature_names=FNames2,class_names=CNames)

graph2 = pydotplus.graph_from_dot_data(dot_data2)

Image(graph2.create_png())
graph2.write_png("CPU_DT.png")
dot_data3 = tree.export_graphviz(DTree3,out_file=None,feature_names=FNames3,class_names=CNames)

graph3 = pydotplus.graph_from_dot_data(dot_data3)

Image(graph3.create_png())
graph3.write_png("NetworkDT.png")



DecisionTreeClassifier(criterion='entropy', max_depth=5) DecisionTreeClassifier(criterion='entropy', max_depth=5) DecisionTreeClassifier(criterion='entropy', max_depth=5)
[1 0 0 ... 0 0 0]
[1 0 1 ... 0 0 0]
[1 0 0 ... 0 0 0]
21545 21545 21545
[1 0 1 ... 0 0 0]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96     12827
           1       0.90      1.00      0.94      8718

    accuracy                           0.95     21545
   macro avg       0.95      0.96      0.95     21545
weighted avg       0.96      0.95      0.95     21545

confusion_matrix:  [[11807  1020]
 [    2  8716]]
accuracy  0.952564400092829


True